name: .NET Core Desktop

on:
  push:
    branches: [ "Master" ]  # Make sure to use the correct branch name
  pull_request:
    branches: [ "Master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: ProgPart1.sln
      Test_Project_Path: your-test-project-path
      Wap_Project_Directory: your-wap-project-directory-name  # Adjust accordingly
      Wap_Project_Path: your-wap-project-path  # Adjust accordingly

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
     

    - name: Execute unit tests
      run: dotnet test || echo "No tests found, skipping..."

    - name: Restore the application
      run: dotnet restore ${{ env.Solution_Name }}
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build the application
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}

    - name: Publish the application
      run: dotnet publish ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --output ./output

    
